##### БАЗОВЫЕ НАСТРОЙКИ #####
set -g default-terminal "screen-256color"
set -g mouse on
set -g escape-time 0
set -g history-limit 10000

##### PREFIX #####
set -g prefix C-f
unbind C-b
bind C-f send-prefix

##### SPLITS #####
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

##### RELOAD CONFIG #####
unbind r
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"

##### RESIZE PANES #####
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

##### TREE #####
bind s choose-tree -sZ -O name

##### INDEXES #####
set -g base-index 1
setw -g pane-base-index 1

##### STATUS BAR (tmux-power) #####
set -g status on
set -g status-position bottom
set -g status-interval 1

##### PLUGINS #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'wfxr/tmux-power'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'

##### RESURRECT / CONTINUUM #####
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

##### TPM #####
run '~/.tmux/plugins/tpm/tpm'

set -g @power_theme 'powerline'
# Левая часть
set -g status-left "#[bold] #{session_name} "
set -g status-left-length 20

# Центральная часть (окна)
set -g @power_window_status_style 'number'

# Правая часть — МОДУЛЬНО
set -g @power_status_right 'git, uptime, time'

# Формат времени
set -g @power_time_format '%H:%M:%S'
